version: 2
registries:
  npm-registry:
    type: "npm-registry"
    url: "https://registry.npmjs.org"
    token: ${{secrets.GH_DUMMY}}
    replaces-base: true
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 12
      semver-patch-days: 7
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'wrangler'