# Cleans up previous GH action queues
name: Clean GH Actions

on:
  push:
    branches: ["main"]

permissions:
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: Cleanup Actions
    uses: theantiscamgroup/workflows/.github/workflows/clean_actions.yml@main
