# Cleans up previous GH action queues
name: Clean GH Actions

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Clean up github job
  cleanup_actions:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Cleanup Actions
        uses: igorjs/gh-actions-clean-workflow@8de2bf6a685b49cbece3bdb16ca5cdb827684161
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          runs_to_keep: 1
          runs_older_than: 0