name: ESLint
on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "eslint.config.ts"
      - "wrangler.toml"
      - "package.json"
      - ".node-version"
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
    paths:
      - "src/**"
      - "eslint.config.ts"
      - "wrangler.toml"
      - "package.json"

permissions:
  contents: read
  security-events: write

jobs:
  run:
    name: Scan
    uses: theantiscamgroup/workflows/.github/workflows/run_eslint.yml@main
    with:
      ref: ${{ github.ref }}