# Syncs discord commands
name: Sync Discord Commands

on:
  push:
    branches: ["main"]
    paths:
      - "src/commands.ts"
      - "src/consts.ts"
      - "src/config.ts"
      - ".github/workflows/sync.yml"

concurrency:
  group: "sync"
  cancel-in-progress: false

permissions:
  deployments: write
  contents: read

jobs:
  command_sync:
    name: Sync Discord Commands
    runs-on: ubuntu-latest
    environment: discord
    steps:
      - name: Checkout
        uses: actions/checkout@v7

        # Install runtime and packages
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          cache: "npm"
          node-version-file: ".node-version"
          package-manager-cache: true
      - name: Install Node Packages
        run: npm install && npm install slash-up@latest

      - name: Sync Commands
        if: success()
        run: npm run sync
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}

  clean_deploys:
    name: Clean Discord Sync Deploys
    uses: theantiscamgroup/workflows/.github/workflows/clean_deploys.yml@main
    secrets: inherit
    with:
      environment: discord